apiVersion: 1

policies:
  - orgId: 1
    receiver: email-warning
    group_by:
      - alertname
      - project
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    routes:
      - receiver: email-critical
        matchers:
          - severity = critical
        continue: false
        group_wait: 10s
        group_interval: 1m
        repeat_interval: 1h
      - receiver: email-warning
        matchers:
          - severity = warning
        continue: false
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 4h
      - receiver: email-dev
        matchers:
          - severity = info
        continue: false
        group_wait: 1m
        group_interval: 10m
        repeat_interval: 12h
